/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2023-01-01 12:42:49 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/kipling_db -t answers -t courses -t exercises -t exercises_files -t files -t questions -t users -t users_courses -s kipling_db
 *
 */


export namespace answersFields {
    export type id = number;
    export type question_id = number;
    export type answer = string;
    export type type = number;
    export type valid = number;
    export type explanation = string | null;

}

export interface answers {
    id: answersFields.id;
    question_id: answersFields.question_id;
    answer: answersFields.answer;
    type: answersFields.type;
    valid: answersFields.valid;
    explanation: answersFields.explanation;

}

export namespace coursesFields {
    export type id = number;
    export type photo = string | null;
    export type name = string;
    export type description = number | null;
    export type trailer_id = number | null;

}

export interface courses {
    id: coursesFields.id;
    photo: coursesFields.photo;
    name: coursesFields.name;
    description: coursesFields.description;
    trailer_id: coursesFields.trailer_id;

}

export namespace exercisesFields {
    export type id = number;
    export type name = string;
    export type exams_id = number;
    export type courses_id = number;

}

export interface exercises {
    id: exercisesFields.id;
    name: exercisesFields.name;
    exams_id: exercisesFields.exams_id;
    courses_id: exercisesFields.courses_id;

}

export namespace exercises_filesFields {
    export type exercises_id = number;
    export type files_id = number;

}

export interface exercises_files {
    exercises_id: exercises_filesFields.exercises_id;
    files_id: exercises_filesFields.files_id;

}

export namespace filesFields {
    export type id = number;
    export type name = string;
    export type unique_name = string;
    export type status = number;

}

export interface files {
    id: filesFields.id;
    name: filesFields.name;
    unique_name: filesFields.unique_name;
    status: filesFields.status;

}

export namespace questionsFields {
    export type id = number;
    export type question = string;
    export type type = number;
    export type exercise_id = number;

}

export interface questions {
    id: questionsFields.id;
    question: questionsFields.question;
    type: questionsFields.type;
    exercise_id: questionsFields.exercise_id;

}

export namespace usersFields {
    export type id = number;
    export type name = string;
    export type password = string;
    export type status = number;

}

export interface users {
    id: usersFields.id;
    name: usersFields.name;
    password: usersFields.password;
    status: usersFields.status;

}

export namespace users_coursesFields {
    export type users_id = number;
    export type courses_id = number;
    export type status = number;

}

export interface users_courses {
    users_id: users_coursesFields.users_id;
    courses_id: users_coursesFields.courses_id;
    status: users_coursesFields.status;

}
